//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantLibDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestaurantModelContainer : DbContext
    {
        public RestaurantModelContainer()
            : base("name=RestaurantModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Filiale> Filialen { get; set; }
        public virtual DbSet<Kunde> Kunden { get; set; }
        public virtual DbSet<Buchung> Bestellungen { get; set; }
        public virtual DbSet<Gericht> Gerichte { get; set; }
    }
}
