//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantLibDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zeitslot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zeitslot()
        {
            this.HatBuchungen = new HashSet<Buchung>();
        }
    
        public int Id { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime Ende { get; set; }
    
        public virtual Filiale Filiale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Buchung> HatBuchungen { get; set; }
    }
}
